import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Root.module.scss';

const Root: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Root</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </div>
  );
};

export default Root;
